### PR TITLE
mod build ci to 500minute for github action

### PR DESCRIPTION
**Pull request by huanghuangzym**
default 3hours 
sometime not enough to build envoy,improve it

### CODE REVIEW

**Comment by huanghuangzym** [comment]
it seemes i do not have enough privalage to request review button
can help to review? @zhaohuabing

**Review by zhaohuabing — APPROVED** [review]
LGTM

**Comment by zhaohuabing** [comment]
It takes so long to build envoy.

**Comment by huanghuangzym** [comment]
> 

maybe  we should use some build cache to avoid compile all file
pr build is better to increment compile?

**Comment by zhaohuabing** [comment]
We should consider using self host runners to build envoy: https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

**Comment by huanghuangzym** [comment]
> We should consider using self host runners to build envoy: https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

i do not have privilige to add self runners in action tab

**Pull request merged**
